# Generated by Django 3.2.8 on 2021-12-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
