# Generated by Django 3.2.8 on 2021-12-08 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_delete_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
